export const orbitStyles = {
  page: { width: "100%", maxWidth: 980 },
  header: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 18, marginBottom: 26, flexWrap: "wrap" },
  eyebrow: { margin: "0 0 9px", color: "var(--primary-dark)", fontWeight: 900, textTransform: "uppercase", letterSpacing: "0.12em", fontSize: 12 },
  title: { margin: 0, fontSize: 42, lineHeight: 1, letterSpacing: "-0.05em", color: "var(--text)" },
  subtitle: { margin: "10px 0 0", color: "var(--muted)", fontWeight: 650, lineHeight: 1.5 },
  sectionTitle: { margin: "28px 0 14px", fontSize: 23, color: "var(--text)", letterSpacing: "-0.025em" },
  card: { padding: 22, background: "var(--surface)", border: "1px solid var(--border)", borderRadius: 26, boxShadow: "var(--shadow)" },
  cardStack: { display: "flex", flexDirection: "column", gap: 14 },
  row: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 16 },
  actions: { display: "flex", gap: 10, flexWrap: "wrap" },
  button: { border: 0, borderRadius: 999, padding: "12px 18px", background: "var(--primary)", color: "white", fontWeight: 900, cursor: "pointer" },
  secondaryButton: { border: "1px solid var(--border)", borderRadius: 999, padding: "11px 17px", background: "var(--surface)", color: "var(--text)", fontWeight: 850, cursor: "pointer" },
  dangerButton: { border: "1px solid color-mix(in srgb, var(--danger) 38%, transparent)", borderRadius: 999, padding: "11px 17px", background: "color-mix(in srgb, var(--danger) 8%, var(--surface))", color: "var(--danger)", fontWeight: 900, cursor: "pointer" },
  input: { width: "100%", boxSizing: "border-box", border: "1px solid var(--border)", borderRadius: 15, padding: "13px 15px", background: "var(--surface)", color: "var(--text)", outline: "none" },
  label: { display: "block", margin: "18px 0 8px", color: "var(--text)", fontWeight: 850 },
  muted: { margin: "6px 0 0", color: "var(--muted)", fontWeight: 650, lineHeight: 1.5 },
  name: { margin: 0, color: "var(--text)", fontSize: 20, letterSpacing: "-0.02em" },
  badge: { display: "inline-flex", padding: "6px 10px", borderRadius: 999, background: "color-mix(in srgb, var(--primary) 12%, transparent)", color: "var(--primary-dark)", fontSize: 12, fontWeight: 900, textTransform: "capitalize" },
  empty: { padding: 34, textAlign: "center", color: "var(--muted)" },
  progressTrack: { height: 10, borderRadius: 999, overflow: "hidden", background: "color-mix(in srgb, var(--primary) 12%, var(--surface))", marginTop: 18 },
  form: { maxWidth: 720 },
};
