import React, { useCallback, useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { toast } from "sonner";
import { formatApiError, projectApi, uploadApi } from "@/lib/api";
import { orbitStyles as s } from "@/pages/orbitStyles";
export default function ProjectDetail() {
  const { projectId } = useParams();
  const navigate = useNavigate();
  const [project, setProject] = useState(null);
  const [proofFor, setProofFor] = useState(null);
  const [proofText, setProofText] = useState('');
  const [proofFile, setProofFile] = useState(null);
  const [busy, setBusy] = useState(null);
  const load = useCallback(async () => { try { const { data } = await projectApi.get(projectId); setProject(data); } catch (err) { toast.error(formatApiError(err.response?.data?.detail) || 'Unable to load project'); } }, [projectId]);
  useEffect(() => { load(); }, [load]);
  async function complete(subtask) { setBusy(subtask.id); try { const { data } = await projectApi.completeSubtask(projectId, subtask.id); if (data.verification_required) { setProofFor(subtask); return; } setProject(data.project); toast.success('Subtask completed'); } catch (err) { toast.error(formatApiError(err.response?.data?.detail) || 'Could not complete subtask'); } finally { setBusy(null); } }
  async function submitProof(e) { e.preventDefault(); if (!proofFor || (!proofText.trim() && !proofFile)) return; setBusy(proofFor.id); try { let proofImageKey = null; if (proofFile) { const contentType = proofFile.type || 'image/jpeg'; const { data: upload } = await uploadApi.createUploadUrl({ upload_type: 'proof_image', filename: proofFile.name, content_type: contentType }); const response = await fetch(upload.upload_url, { method: 'PUT', headers: upload.headers, body: proofFile }); if (!response.ok) throw new Error('Image upload failed'); proofImageKey = upload.key; } await projectApi.submitSubtaskVerification(projectId, proofFor.id, { verification_text: proofText.trim(), verification_photo_url: proofImageKey }); setProofFor(null); setProofText(''); setProofFile(null); await load(); toast.success('Proof submitted'); } catch (err) { toast.error(formatApiError(err.response?.data?.detail || err.message) || 'Could not submit proof'); } finally { setBusy(null); } }
  if (!project) return <p style={s.muted}>Loading project...</p>;
  return <div style={s.page}><header style={s.header}><div><p style={s.eyebrow}>{project.orbit_id ? 'Orbit Project' : 'Personal Project'}</p><h1 style={s.title}>{project.title}</h1><p style={s.subtitle}>{project.description}</p></div><button style={s.secondaryButton} onClick={() => navigate(project.orbit_id ? '/orbits/' + project.orbit_id : '/projects')}>Back</button></header><section style={s.card}><div style={s.row}><strong>{project.completed_subtasks || 0}/{project.total_subtasks || 0} subtasks</strong><span style={s.badge}>{project.completion_percent || 0}%</span></div><div style={s.progressTrack}><div style={{ height: '100%', width: (project.completion_percent || 0) + '%', background: 'var(--primary)' }} /></div><p style={s.muted}>{project.xp_reward || 0} XP - {project.coin_reward || 0} coins on project completion</p></section><h2 style={s.sectionTitle}>Subtasks</h2><div style={s.cardStack}>{(project.subtasks || []).map((subtask) => <article key={subtask.id} style={s.card}><div style={s.row}><div><h3 style={s.name}>{subtask.completed ? 'Done: ' : ''}{subtask.title}</h3><p style={s.muted}>{subtask.xp_reward || 0} XP - {subtask.coin_reward || 0} coins - {subtask.verification_status || 'not_required'}</p></div><button style={subtask.completed ? s.secondaryButton : s.button} disabled={subtask.completed || busy === subtask.id} onClick={() => complete(subtask)}>{subtask.completed ? 'Completed' : 'Complete'}</button></div></article>)}</div>{proofFor && <form style={{ ...s.card, marginTop: 18 }} onSubmit={submitProof}><h3 style={s.name}>Submit proof for {proofFor.title}</h3><textarea style={{ ...s.input, minHeight: 120 }} value={proofText} onChange={(e) => setProofText(e.target.value)} placeholder="Describe what you completed" /><label style={s.label}>Proof image optional</label><input type="file" accept="image/jpeg,image/png,image/webp,image/heic,.heic" onChange={(e) => setProofFile(e.target.files?.[0] || null)} />{proofFile && <p style={s.muted}>{proofFile.name}</p>}<div style={s.actions}><button type="button" style={s.secondaryButton} onClick={() => { setProofFor(null); setProofFile(null); }}>Cancel</button><button style={s.button} disabled={(!proofText.trim() && !proofFile) || busy}>Submit proof</button></div></form>}</div>;
}
