import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { orbitApi } from "@/lib/api";
import { orbitStyles as s } from "@/pages/orbitStyles";

const FALLBACK = [
  { id: "family", name: "Family Orbit", category: "Home", theme_id: "family", featured: true, premium: false, version: 1, description: "Shared goals, chores, rewards, and family accountability.", summary: ["Habits", "Rewards", "Milestones", "Roles"] },
  { id: "scout_troop", name: "Scout Troop Orbit", category: "Scouting", theme_id: "scout", featured: true, premium: false, version: 1, description: "Meetings, campouts, service projects, leadership, and troop accountability.", summary: ["Patrols", "Readiness", "Events", "Roles"] },
  { id: "couples", name: "Couples Orbit", category: "Relationships", theme_id: "sunset", featured: true, premium: false, version: 1, description: "Shared goals, date nights, gratitude, and relationship milestones.", summary: ["Habits", "Rewards", "Events", "Milestones"] },
  { id: "accountability_circle", name: "Accountability Circle", category: "Goals", theme_id: "default", featured: false, premium: false, version: 1, description: "Weekly check-ins, shared goals, and group accountability.", summary: ["Check-ins", "Rewards", "Challenges"] },
  { id: "fitness_group", name: "Fitness Group", category: "Fitness", theme_id: "fitness", featured: false, premium: false, version: 1, description: "Workouts, step goals, fitness challenges, and team motivation.", summary: ["Challenges", "Events", "Rewards"] },
  { id: "study_group", name: "Study Group", category: "Learning", theme_id: "study", featured: false, premium: false, version: 1, description: "Study sessions, reading goals, exam prep, and group focus.", summary: ["Study habits", "Events", "Projects"] },
  { id: "blank", name: "Blank Orbit", category: "Custom", theme_id: "default", featured: false, premium: false, version: 1, description: "Start with an empty Orbit and customize everything yourself.", summary: ["Private", "Invite-only", "Flexible"] },
];
function itemsOf(data) { return Array.isArray(data) ? data : data?.items || data?.templates || []; }
export default function TemplateMarketplace() {
  const navigate = useNavigate();
  const [templates, setTemplates] = useState(FALLBACK);
  const [selected, setSelected] = useState(null);
  useEffect(() => { orbitApi.listTemplates().then(({ data }) => { const remote = itemsOf(data); if (remote.length) setTemplates(FALLBACK.map((item) => ({ ...item, ...(remote.find((r) => r.id === item.id || r.template_id === item.id) || {}) }))); }).catch(() => {}); }, []);
  return <div style={s.page}><header style={s.header}><div><p style={s.eyebrow}>Templates</p><h1 style={s.title}>Template Marketplace</h1><p style={s.subtitle}>Create an Orbit for your family, troop, fitness group, study group, couple, or accountability circle.</p></div><button style={s.button} onClick={() => navigate('/orbits/new')}>Create Orbit</button></header><div style={styles.grid}>{templates.map((template) => <button key={template.id} style={{ ...s.card, ...styles.card, borderColor: template.featured ? 'var(--primary)' : 'var(--border)' }} onClick={() => setSelected(template)}><div style={styles.preview}><span>{template.theme_id || 'default'}</span></div><p style={s.eyebrow}>{template.category} {template.premium ? 'Premium' : ''}</p><h2 style={s.name}>{template.name}</h2><p style={s.muted}>{template.description}</p><div style={s.actions}>{(template.summary || []).map((item) => <span key={item} style={s.badge}>{item}</span>)}</div></button>)}</div>{selected && <section style={{ ...s.card, marginTop: 22 }}><div style={s.row}><div><p style={s.eyebrow}>Template detail</p><h2 style={s.name}>{selected.name}</h2><p style={s.muted}>{selected.description}</p></div><button style={s.secondaryButton} onClick={() => setSelected(null)}>Close</button></div><div style={styles.detailGrid}>{['Habits', 'Rewards', 'Projects', 'Milestones', 'Roles'].map((label) => <div key={label} style={styles.detailItem}><strong>{label}</strong><p style={s.muted}>{selected.id !== 'blank' ? 'Included or recommended by this template.' : 'Customize this after creation.'}</p></div>)}</div><button style={{ ...s.button, marginTop: 18 }} onClick={() => navigate('/orbits/new?template=' + selected.id)}>Create Orbit</button></section>}</div>;
}
const styles = { grid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 16 }, card: { textAlign: 'left', cursor: 'pointer' }, preview: { height: 96, borderRadius: 22, marginBottom: 16, background: 'linear-gradient(135deg, var(--primary), var(--primary-dark))', display: 'flex', alignItems: 'end', padding: 14, color: 'white', fontWeight: 900, textTransform: 'capitalize' }, detailGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: 12, marginTop: 18 }, detailItem: { padding: 14, border: '1px solid var(--border)', borderRadius: 18, background: 'var(--bg)' } };
